apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-init-sql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  init.sql: |-
{{ .Files.Get "initial.sql" | indent 4 }}
