---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-mysql
spec:
  selector:
    app: {{ .Values.app.name }}-mysql
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}-mysql
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}-mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ .Values.app.name }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-mysql
        app.kubernetes.io/name: {{ .Values.app.name }}-mysql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
      volumes:
        - name: init-script
          configMap:
            name: {{ .Values.app.name }}-init-sql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mysql.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
