apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}-mysql
spec:
  serviceName: {{ .Values.app.name }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-mysql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: 
                - /bin/sh
                - -c
                - mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            exec:
              command: 
                - /bin/sh
                - -c
                - mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          securityContext:
            runAsUser: 999
            runAsGroup: 999
      volumes:
        - name: init-script
          configMap:
            name: {{ .Values.app.name }}-init-sql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mysql.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}