apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-mysql-pvc
