apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}-mysql
spec:
  serviceName: {{ .Values.app.name }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mysql.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
