apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-login
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/0xsaju/sample-login.git
    targetRevision: dev_ci_cd_without_mysql
    path: helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-login
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
