apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-login
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/0xsaju/sample-login.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: mysql.persistence.storageClass
          value: local-path
        - name: app.uploads.storageClass
          value: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-login
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
