apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  type: Z2l0  # "git" in base64
  url: aHR0cHM6Ly9naXRodWIuY29tLzB4c2FqdS9zYW1wbGUtbG9naW4uZ2l0  # URL in base64
  username: MHhzYWp1  # username in base64
  password: ${GITHUB_PAT}  # Will be replaced with base64 encoded PAT
