apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/0xsaju/sample-login.git
  username: 0xsaju
  password: ${GITHUB_PAT}
