apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/0xsaju/sample-login.git  # Added .git extension
  username: 0xsaju
  password: ${GITHUB_PAT}  # Will be replaced during deployment
