apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-pat
  namespace: argocd
spec:
  template:
    metadata:
      name: github-pat
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    type: Opaque
  # The encrypted data will be added by kubeseal
