replicaCount: 2  # Increase for HA

app:
  name: sample-login
  image:
    repository: 0xsaju/sample-login
    tag: ff4ab0c8e159677065ab1c7d08a7de9fdc02d05b
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 300m      # Changed value to trigger sync
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  uploads:
    size: 5Gi       # Increase for production
    storageClass: "local-path"  # Change to match your available storage class

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "login.example.com"  # You can use your node IP instead for testing
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Removed TLS for initial testing

mysql:
  image:
    repository: 0xsaju/sample-login
    tag: ff4ab0c8e159677065ab1c7d08a7de9fdc02d05b
  rootPassword: "mysecretpassword"  # Set a default password for testing
  database: sample_login
  service:
    port: 3306
  persistence:
    size: 10Gi      # Increase for production
    storageClass: "local-path"  # Change to match your available storage class
  resources:
    limits:
      cpu: 1000m    # Increase for production
      memory: 1Gi
    requests:
      cpu: 200m      # Reduced for testing
      memory: 256Mi  # Reduced for testing
