replicaCount: 1

app:
  name: sample-login
  image:
    repository: sample-login
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: 192.168.56.101
      paths:
        - path: /
          pathType: Prefix

mysql:
  image:
    repository: mysql
    tag: "8.0"
  rootPassword: "mysecretpassword"  # Change this in production
  database: sample_login
  service:
    port: 3306
  persistence:
    size: 1Gi
    storageClass: "local-path"  # Change based on your cluster's storage class
  initializationEnabled: true
