replicaCount: 1

app:
  name: sample-login
  image:
    repository: sample-login
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  uploads:
    size: 1Gi
    storageClass: "local-path"
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: 192.168.56.101
      paths:
        - path: /
          pathType: Prefix
