replicaCount: 2  # Increase for HA

app:
  name: sample-login
  image:
    repository: 0xsaju/sample-login
    tag: 4d7cb63a9055671d95407427be527704f87ebc8b
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 300m      # Changed value to trigger sync
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  uploads:
    size: 5Gi       # Increase for production
    storageClass: "local-path"  # Change to match your available storage class

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "login.example.com"  # You can use your node IP instead for testing
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Removed TLS for initial testing

mysql:
  image:
    repository: 0xsaju/sample-login
    tag: 4d7cb63a9055671d95407427be527704f87ebc8b
  rootPassword: "mysecretpassword"
  database: sample_login
  service:
    port: 3306
  persistence:
    size: 1Gi      # Reduced for testing
    storageClass: "local-path"
  resources:
    limits:
      cpu: 500m    # Reduced for testing
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
      #test
