replicaCount: 1

app:
  name: sample-login
  image:
    repository: 0xsaju/sample-login  # Updated to match prod
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  uploads:
    size: 1Gi
    storageClass: "local-path"
  resources:
    limits:
      cpu: "300m"      # Synced with prod
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: "192.168.56.101.nip.io"  # Updated to use nip.io
      paths:
        - path: /
          pathType: Prefix
