name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov bandit safety
          
      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml
          
      - name: Security scan
        run: |
          bandit -r ./ -f json -o bandit-report.json
          safety check

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            0xsaju/sample-login-app:latest
            0xsaju/sample-login-app:${{ github.sha }}
          cache-from: type=registry,ref=0xsaju/sample-login-app:buildcache
          cache-to: type=registry,ref=0xsaju/sample-login-app:buildcache,mode=max

      - name: Update values file
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s/tag: .*/tag: ${{ github.sha }}/" helm/values-prod.yaml
          
      - name: Commit changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add helm/values-prod.yaml
          git commit -m "Update production image tag to ${{ github.sha }} [skip ci]" || echo "No changes to commit"
          git push

      - name: Scan container image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '0xsaju/sample-login-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
