name: CI/CD Pipeline

on:
  push:
    branches: [ dev_ci_cd_v1 ]
  pull_request:
    branches: [ dev_ci_cd_v1 ]

env:
  DOCKER_IMAGE: 0xsaju/sample-login
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Update Helm values
        run: |
          sed -i "s|repository: .*|repository: ${{ env.DOCKER_IMAGE }}|" helm/values-prod.yaml
          sed -i "s|tag: .*|tag: ${{ github.sha }}|" helm/values-prod.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add helm/values-prod.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push
